---

- name: Verification Tasks
  hosts: 127.0.0.1
  connection: local
  become: yes
  gather_facts: yes
  tasks:
  - name: Install ansible packages
    apt:
      name: "{{ ansible_packages_utils }}"
      update_cache: yes
    vars:
      ansible_packages_utils:
      - rsync
      - tar
      - wget
      - curl
      - tcpdump
      - python-pip
      - python3-pip

#- name: GCP Scout Scanner - Baseline
#  hosts: 127.0.0.1
#  connection: local
#  become: yes
#  roles:
#    - ./../roles/gcp_scout
